steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/build/firebase', '.']
images: ['us-docker.pkg.dev/$PROJECT_ID/build/firebase']
options:
  logging: CLOUD_LOGGING_ONLY
